//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityApplication
    {
        public long ID { get; set; }
        public string ApplicationCode { get; set; }
        public string ApplicationName { get; set; }
        public string FullName { get; set; }
        public string Remarks { get; set; }
        public string ActiveFlag { get; set; }
    }
}
